name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. The more detail you provide, the faster we can fix it.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: When I run X, I expect Y but get Z.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How do we reproduce this?
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, shell version, OpenClaw version if relevant
      placeholder: |
        OS: Ubuntu 24.04 / macOS 15
        Shell: bash 5.2
        OpenClaw: 2026.2.21
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant output or logs
      description: Paste any relevant command output. Remove sensitive values (ledger paths, tokens).
      render: shell
    validations:
      required: false
